// pages/index.tsx
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";
import DateTimePicker from 'react-datetime-picker/dist/entry.nostyle';

const addStock = () => {
  const [value, onChange] = useState(new Date());

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form
          action="/send-data-here"
          method="post"
          style={{ display: "flex", flexDirection: "column" }}
        >
          <label>Ticker:</label>
          <input type="text" id="first" name="first" />
          <label>Open Price:</label>
          <input type="text" id="last" name="last" />
          <label>Close Price:</label>
          <input type="text" id="last" name="last" />

          <label>Date & Time:</label>
          <DateTimePicker onChange={onChange} value={value} />

          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  );
};

export default addStock;
