import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

type stockData = {
  ticker: { S: string };
  open_price: { N: string };
  close_price: { N: string };
  date_time: { N: string };
};

export default function Home() {
  const [input, setInput] = useState("");
  const [data, setData] = useState<stockData | null>(null);
  const [error, setError] = useState<string>("");

  const getStockData = (stockTicker: string) => {
    console.log("get stock data called");
    fetch(
      `https://rmlqm75bw7.execute-api.us-west-1.amazonaws.com/api/v1/stock?ticker=${stockTicker}`
    )
      .then((res) => res.json())
      .then((data) => {
        if (data?.Item) {
          setError("");
          setData(data.Item);
        } else {
          setError("This ticker is not currently stored");
        }
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  };

  const handleKeyDown = (event: { key: string }) => {
    if (event.key === "Enter") {
      getStockData(input);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <button className="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
            <a href="/addStock"> Add Stock</a>
          </button>
          <p>
            created with &nbsp;
            <code className={styles.code}>
              CDK, ExpressJs, Docker, and Next.js
            </code>
          </p>
        </div>

        <div className={styles.center}>
          <h2>Stonk 📈</h2>
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            className="form-control p-2 mr-2  border-solid border-2 rounded-2xl focus:outline-none placeholder:text-black "
            type="search"
            id="stock"
            name="stock"
            placeholder="enter ticker here"
          />
          <button
            className="mt-3 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded"
            onClick={() => getStockData(input)}
          >
            Search
          </button>
        </div>
        {error && <h3>{error}</h3>}
        {data && (
          <table className="table-auto">
            <thead>
              <tr>
                <th>Ticker</th>
                <th>Close Price</th>
                <th>Open Price</th>
                <th>Date & Time</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{data.ticker.S}</td>
                <td>${data.close_price.N}</td>
                <td>${data.open_price.N}</td>
                <td>{new Date(parseInt(data.date_time.N, 10)).toString()}</td>
              </tr>
            </tbody>
          </table>
        )}
        <div className={styles.grid}></div>
      </main>
    </>
  );
}
